{
 "title": "Overview - FR",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "SelectedSourceCar",
    "label": "SelectedSourceCar",
    "query": {
     "query": "label_values(pitwall_air_temperature_celsius,Car)"
    }
   },
   {
    "name": "SelectedSourcePilot",
    "label": "SelectedSourcePilot",
    "query": {
     "query": "label_values(pitwall_air_temperature_celsius,Pilot)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temps au tour valides",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "expr": "pitwall_laptimes_seconds{Car=\"$SelectedSourceCar\", Pilot=\"$SelectedSourcePilot\"} != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tps au tour moyen",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(Car) (pitwall_laptimes_seconds{Car=\"$SelectedSourceCar\", Pilot=\"$SelectedSourcePilot\"}) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conditions de course",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature Piste",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pitwall_track_temperature_celsius{Car=\"$SelectedSourceCar\", Pilot=\"$SelectedSourcePilot\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Humidité moy piste %",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pitwall_road_wetness_avg_percent{Car=\"$SelectedSourceCar\", Pilot=\"$SelectedSourcePilot\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Air Temperature",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pitwall_air_temperature_celsius{Car=\"$SelectedSourceCar\", Pilot=\"$SelectedSourcePilot\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Carburant", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Fuel",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pitwall_fuel_volume{Car=\"$SelectedSourceCar\", Pilot=\"$SelectedSourcePilot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conso L/Lap",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pitwall_computed_consumedfuelperlap_volume{Car=\"$SelectedSourceCar\", Pilot=\"$SelectedSourcePilot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temps restant fuel",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pitwall_computed_remainingtimeonfuel_seconds{Car=\"$SelectedSourceCar\", Pilot=\"$SelectedSourcePilot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nb tour restant fuel",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pitwall_computed_remaininglap_volume{Car=\"$SelectedSourceCar\", Pilot=\"$SelectedSourcePilot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 } },
  {
   "title": "Conso L/Lap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "pitwall_computed_consumedfuelperlap_volume{Car=\"$SelectedSourceCar\", Pilot=\"$SelectedSourcePilot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pneumatiques", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Usure AvGauche",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 25 },
   "repeat": "SelectedCarLabel",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pitwall_tyres_wear_frontleft_percent{Car=\"$SelectedSourceCar\", Pilot=\"$SelectedSourcePilot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usure AvDroite",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pitwall_tyres_wear_frontright_percent{Car=\"$SelectedSourceCar\", Pilot=\"$SelectedSourcePilot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AvGauche Delta Usure 10min",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(pitwall_tyres_wear_frontleft_percent{Pilot=\"$SelectedSourcePilot\", Car=\"$SelectedSourceCar\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AvDroite Delta Usure 10min",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(pitwall_tyres_wear_frontright_percent{Pilot=\"$SelectedSourcePilot\", Car=\"$SelectedSourceCar\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AvGauche Restant min",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(pitwall_tyres_wear_frontleft_percent{Pilot=\"$SelectedSourcePilot\", Car=\"$SelectedSourceCar\"})/abs(delta(pitwall_tyres_wear_frontleft_percent{Pilot=\"$SelectedSourcePilot\", Car=\"$SelectedSourceCar\"}[10m]))*10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AvDroite Restant min",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(pitwall_tyres_wear_frontright_percent{Pilot=\"$SelectedSourcePilot\", Car=\"$SelectedSourceCar\"})/abs(delta(pitwall_tyres_wear_frontright_percent{Pilot=\"$SelectedSourcePilot\", Car=\"$SelectedSourceCar\"}[10m]))*10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usure ArGauche",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pitwall_tyres_wear_rearleft_percent{Car=\"$SelectedSourceCar\", Pilot=\"$SelectedSourcePilot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usure ArDroite",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pitwall_tyres_wear_rearright_percent{Car=\"$SelectedSourceCar\", Pilot=\"$SelectedSourcePilot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ArGauche Delta Usure 10min",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(pitwall_tyres_wear_rearleft_percent{Pilot=\"$SelectedSourcePilot\", Car=\"$SelectedSourceCar\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ArDroite Delta Usure 10min",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(pitwall_tyres_wear_rearright_percent{Pilot=\"$SelectedSourcePilot\", Car=\"$SelectedSourceCar\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ArGauche Restant min",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(pitwall_tyres_wear_rearleft_percent{Pilot=\"$SelectedSourcePilot\", Car=\"$SelectedSourceCar\"})/abs(delta(pitwall_tyres_wear_rearleft_percent{Pilot=\"$SelectedSourcePilot\", Car=\"$SelectedSourceCar\"}[10m]))*10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ArDroit Restant min",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(pitwall_tyres_wear_rearright_percent{Pilot=\"$SelectedSourcePilot\", Car=\"$SelectedSourceCar\"})/abs(delta(pitwall_tyres_wear_rearright_percent{Pilot=\"$SelectedSourcePilot\", Car=\"$SelectedSourceCar\"}[10m]))*10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usure Pneus",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "pitwall_tyres_wear_frontleft_percent{Car=\"$SelectedSourceCar\", Pilot=\"$SelectedSourcePilot\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pitwall_tyres_wear_frontright_percent{Car=\"$SelectedSourceCar\", Pilot=\"$SelectedSourcePilot\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pitwall_tyres_wear_rearleft_percent{Car=\"$SelectedSourceCar\", Pilot=\"$SelectedSourcePilot\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pitwall_tyres_wear_rearright_percent{Car=\"$SelectedSourceCar\", Pilot=\"$SelectedSourcePilot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Températures Pneus",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "pitwall_tyres_temperatures_frontleft_celsius{Car=\"$SelectedSourceCar\", Pilot=\"$SelectedSourcePilot\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pitwall_tyres_temperatures_frontright_celsius{Car=\"$SelectedSourceCar\", Pilot=\"$SelectedSourcePilot\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pitwall_tyres_temperatures_rearleft_celsius{Car=\"$SelectedSourceCar\", Pilot=\"$SelectedSourcePilot\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pitwall_tyres_temperatures_rearright_celsius{Car=\"$SelectedSourceCar\", Pilot=\"$SelectedSourcePilot\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}