{
 "title": "Beta - Pits",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "SelectedSourceCar",
    "label": "SelectedSourceCar",
    "query": {
     "query": "label_values(pitwall_leaderboard_isinpitlane,SourceCar)"
    }
   },
   {
    "name": "SelectedSourcePilot",
    "label": "SelectedSourcePilot",
    "query": {
     "query": "label_values(pitwall_leaderboard_isinpitlane,SourcePilot)"
    }
   },
   {
    "name": "FocusOnCar",
    "label": "FocusOnCar",
    "query": {
     "query": "label_values(pitwall_leaderboard_isinpitlane,Car)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Pits",
   "type": "table",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(Car) (pitwall_leaderboard_isinpitlane{SourceCar=\"$SelectedSourceCar\", SourcePilot=\"$SelectedSourcePilot\"}) == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Focus on car",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "pitwall_leaderboard_isinpitlane{SourceCar=\"$SelectedSourceCar\", SourcePilot=\"$SelectedSourcePilot\", Car=\"$FocusOnCar\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All pits",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 21, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "pitwall_leaderboard_isinpitlane{SourceCar=\"$SelectedSourceCar\", SourcePilot=\"$SelectedSourcePilot\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}